import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  EN: {
    // Header
    searchPlaceholder: "Search schemes...",
    login: "Login",
    logout: "Logout",
    settings: "Settings",
    
    // Hero Section
    heroTitle: "Your AI-Powered",
    heroSubtitle: "Rights Assistant",
    heroDescription: "Advanced AI platform that analyzes your documents, understands your needs, discovers hidden benefits, provides personalized recommendations, and guides you through applications - all in your language.",
    startAnalysis: "Start AI Analysis",
    exploreTools: "Explore AI Tools",
    trustedUsers: "Trusted by 50,000+ users",
    
    // Features
    smartDocumentAI: "Smart Document AI",
    smartDocumentDesc: "Extracts & analyzes any document type with 99% accuracy",
    personalizedInsights: "Personalized Insights", 
    personalizedDesc: "AI recommendations tailored to your unique profile",
    voiceTextAI: "Voice & Text AI",
    voiceTextDesc: "Speak naturally in 12+ languages or type details",
    endToEndGuidance: "End-to-End Guidance",
    endToEndDesc: "From discovery to application completion",
    
    // Upload Section
    advancedAI: "Advanced AI Intelligence",
    intelligentAnalysis: "Intelligent Document Analysis",
    uploadDescription: "Our AI understands documents, extracts profiles, analyzes eligibility, discovers hidden benefits, and provides personalized recommendations - all through advanced machine learning.",
    dragDrop: "Drag & Drop Documents",
    clickBrowse: "or click to browse • Supports PDF, JPG, PNG • Max 10MB",
    takePhoto: "Take Photo",
    takePhotoDesc: "Capture documents with your camera",
    voiceInput: "Voice Input",
    voiceInputDesc: "Speak your details",
    typeDetails: "Type Details",
    typeDetailsDesc: "Manually enter your information",
    
    // Stats
    schemes: "Schemes",
    users: "Users", 
    languages: "Languages",
    successRate: "Success Rate",
    aiModels: "AI Models Used",
    aiAccuracy: "AI Accuracy",
    aiAssistant: "AI Assistant",
    
    // CTA Section
    readyToStart: "Ready to Get Started?",
    experienceAI: "Experience AI-Powered Governance",
    ctaDescription: "Advanced AI analyzes your profile in under 30 seconds, discovers hidden benefits, and provides personalized guidance. Join 50,000+ users leveraging AI for their rights!",
    learnMore: "Learn More",
    aiPoweredAnalysis: "AI-Powered Analysis",
    aiAnalysisDesc: "Advanced machine learning models",
    intelligentInsights: "Intelligent Insights",
    intelligentInsightsDesc: "Personalized recommendations",
    voiceDocumentAI: "Voice & Document AI",
    voiceDocumentDesc: "Multi-modal AI processing",
    
    // Upload Section Extended
    uploading: "Uploading document...",
    extracting: "Extracting text...",
    analyzing: "Analyzing with AI...",
    profileExtracted: "Profile extracted successfully!",
    complete: "Complete!",
    processingFailed: "Processing Failed",
    tryAgain: "Try Again",
    enterDetails: "Enter Your Details",
    cancel: "Cancel",
    analyzeText: "Analyze Text",
    
    // Results Section
    eligibilityResults: "Eligibility Results",
    foundSchemes: "Found Schemes",
    eligible: "Eligible",
    notEligible: "Not Eligible",
    maybeEligible: "Maybe Eligible",
    viewDetails: "View Details",
    applyNow: "Apply Now",
    
    // Footer
    madeWithLove: "Made with dedication for India",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    contactUs: "Contact Us"
  },
  
  HI: {
    // Header
    searchPlaceholder: "योजनाएं खोजें...",
    login: "लॉगिन",
    logout: "लॉगआउट", 
    settings: "सेटिंग्स",
    
    // Hero Section
    heroTitle: "आपका AI-संचालित",
    heroSubtitle: "अधिकार सहायक",
    heroDescription: "उन्नत AI प्लेटफॉर्म जो आपके दस्तावेजों का विश्लेषण करता है, आपकी जरूरतों को समझता है, छुपे हुए लाभ खोजता है, व्यक्तिगत सिफारिशें प्रदान करता है, और आवेदनों के माध्यम से मार्गदर्शन करता है - सब आपकी भाषा में।",
    startAnalysis: "AI विश्लेषण शुरू करें",
    exploreTools: "AI टूल्स एक्सप्लोर करें",
    trustedUsers: "50,000+ उपयोगकर्ताओं द्वारा भरोसेमंद",
    
    // Features
    smartDocumentAI: "स्मार्ट दस्तावेज़ AI",
    smartDocumentDesc: "99% सटीकता के साथ किसी भी दस्तावेज़ प्रकार को निकालता और विश्लेषित करता है",
    personalizedInsights: "व्यक्तिगत अंतर्दृष्टि",
    personalizedDesc: "आपकी अनूठी प्रोफ़ाइल के अनुकूल AI सिफारिशें",
    voiceTextAI: "आवाज़ और टेक्स्ट AI",
    voiceTextDesc: "12+ भाषाओं में प्राकृतिक रूप से बोलें या विवरण टाइप करें",
    endToEndGuidance: "संपूर्ण मार्गदर्शन",
    endToEndDesc: "खोज से आवेदन पूर्णता तक",
    
    // Upload Section
    advancedAI: "उन्नत AI बुद्धिमत्ता",
    intelligentAnalysis: "बुद्धिमान दस्तावेज़ विश्लेषण",
    uploadDescription: "हमारा AI दस्तावेजों को समझता है, प्रोफाइल निकालता है, पात्रता का विश्लेषण करता है, छुपे हुए लाभ खोजता है, और व्यक्तिगत सिफारिशें प्रदान करता है - सब उन्नत मशीन लर्निंग के माध्यम से।",
    dragDrop: "दस्तावेज़ खींचें और छोड़ें",
    clickBrowse: "या ब्राउज़ करने के लिए क्लिक करें • PDF, JPG, PNG समर्थित • अधिकतम 10MB",
    takePhoto: "फोटो लें",
    takePhotoDesc: "अपने कैमरे से दस्तावेज़ कैप्चर करें",
    voiceInput: "आवाज़ इनपुट",
    voiceInputDesc: "अपने विवरण बोलें",
    typeDetails: "विवरण टाइप करें",
    typeDetailsDesc: "मैन्युअल रूप से अपनी जानकारी दर्ज करें",
    
    // Stats
    schemes: "योजनाएं",
    users: "उपयोगकर्ता",
    languages: "भाषाएं", 
    successRate: "सफलता दर",
    aiModels: "AI मॉडल उपयोग",
    aiAccuracy: "AI सटीकता",
    aiAssistant: "AI सहायक",
    
    // CTA Section
    readyToStart: "शुरू करने के लिए तैयार?",
    experienceAI: "AI-संचालित शासन का अनुभव करें",
    ctaDescription: "उन्नत AI 30 सेकंड से कम में आपकी प्रोफ़ाइल का विश्लेषण करता है, छुपे हुए लाभ खोजता है, और व्यक्तिगत मार्गदर्शन प्रदान करता है। अपने अधिकारों के लिए AI का लाभ उठाने वाले 50,000+ उपयोगकर्ताओं से जुड़ें!",
    learnMore: "और जानें",
    aiPoweredAnalysis: "AI-संचालित विश्लेषण",
    aiAnalysisDesc: "उन्नत मशीन लर्निंग मॉडल",
    intelligentInsights: "बुद्धिमान अंतर्दृष्टि",
    intelligentInsightsDesc: "व्यक्तिगत सिफारिशें",
    voiceDocumentAI: "आवाज़ और दस्तावेज़ AI",
    voiceDocumentDesc: "मल्टी-मोडल AI प्रसंस्करण",
    
    // Upload Section Extended
    uploading: "दस्तावेज़ अपलोड हो रहा है...",
    extracting: "टेक्स्ट निकाला जा रहा है...",
    analyzing: "AI के साथ विश्लेषण...",
    profileExtracted: "प्रोफ़ाइल सफलतापूर्वक निकाली गई!",
    complete: "पूर्ण!",
    processingFailed: "प्रसंस्करण असफल",
    tryAgain: "पुनः प्रयास करें",
    enterDetails: "अपने विवरण दर्ज करें",
    cancel: "रद्द करें",
    analyzeText: "टेक्स्ट का विश्लेषण करें",
    
    // Results Section
    eligibilityResults: "पात्रता परिणाम",
    foundSchemes: "मिली योजनाएं",
    eligible: "पात्र",
    notEligible: "अपात्र",
    maybeEligible: "संभावित पात्र",
    viewDetails: "विवरण देखें",
    applyNow: "अभी आवेदन करें",
    
    // Footer
    madeWithLove: "भारत के लिए समर्पण से बनाया गया",
    privacyPolicy: "गोपनीयता नीति",
    termsOfService: "सेवा की शर्तें",
    contactUs: "संपर्क करें"
  },
  
  BN: {
    searchPlaceholder: "স্কিম খুঁজুন...",
    login: "লগইন",
    logout: "লগআউট",
    settings: "সেটিংস",
    heroTitle: "আপনার AI-চালিত",
    heroSubtitle: "অধিকার সহায়ক",
    heroDescription: "উন্নত AI প্ল্যাটফর্ম যা আপনার নথি বিশ্লেষণ করে, আপনার প্রয়োজন বোঝে, লুকানো সুবিধা আবিষ্কার করে এবং ব্যক্তিগতকৃত সুপারিশ প্রদান করে।",
    startAnalysis: "AI বিশ্লেষণ শুরু করুন",
    exploreTools: "AI টুলস অন্বেষণ করুন",
    trustedUsers: "৫০,০০০+ ব্যবহারকারীর বিশ্বস্ত",
    smartDocumentAI: "স্মার্ট নথি AI",
    smartDocumentDesc: "99% নির্ভুলতার সাথে যেকোনো নথির ধরণ নিষ্কাশন ও বিশ্লেষণ",
    personalizedInsights: "ব্যক্তিগত অন্তর্দৃষ্টি",
    personalizedDesc: "আপনার অনন্য প্রোফাইলের জন্য AI সুপারিশ",
    voiceTextAI: "ভয়েস ও টেক্সট AI",
    voiceTextDesc: "12+ ভাষায় প্রাকৃতিকভাবে কথা বলুন বা বিবরণ টাইপ করুন",
    endToEndGuidance: "সম্পূর্ণ নির্দেশনা",
    endToEndDesc: "আবিষ্কার থেকে আবেদন সমাপ্তি পর্যন্ত",
    advancedAI: "উন্নত AI বুদ্ধিমত্তা",
    intelligentAnalysis: "বুদ্ধিমান নথি বিশ্লেষণ",
    uploadDescription: "আমাদের AI নথিগুলি বুঝতে পারে, প্রোফাইল নিষ্কাশন করে, যোগ্যতা বিশ্লেষণ করে, লুকানো সুবিধা আবিষ্কার করে এবং ব্যক্তিগত সুপারিশ প্রদান করে।",
    dragDrop: "নথি টেনে এনে ছেড়ে দিন",
    clickBrowse: "বা ব্রাউজ করতে ক্লিক করুন • PDF, JPG, PNG সমর্থিত • সর্বোচ্চ 10MB",
    takePhoto: "ছবি তুলুন",
    takePhotoDesc: "আপনার ক্যামেরা দিয়ে নথি ক্যাপচার করুন",
    voiceInput: "ভয়েস ইনপুট",
    voiceInputDesc: "আপনার বিবরণ বলুন",
    typeDetails: "বিবরণ টাইপ করুন",
    typeDetailsDesc: "ম্যানুয়ালি আপনার তথ্য প্রবেশ করুন",
    schemes: "স্কিম",
    users: "ব্যবহারকারী",
    languages: "ভাষা",
    successRate: "সফলতার হার",
    aiModels: "AI মডেল ব্যবহৃত",
    aiAccuracy: "AI নির্ভুলতা",
    aiAssistant: "AI সহায়ক",
    readyToStart: "শুরু করার জন্য প্রস্তুত?",
    experienceAI: "AI-চালিত শাসনের অভিজ্ঞতা নিন",
    ctaDescription: "উন্নত AI 30 সেকেন্ডের কম সময়ে আপনার প্রোফাইল বিশ্লেষণ করে, লুকানো সুবিধা আবিষ্কার করে এবং ব্যক্তিগত নির্দেশনা প্রদান করে।",
    learnMore: "আরো জানুন",
    aiPoweredAnalysis: "AI-চালিত বিশ্লেষণ",
    aiAnalysisDesc: "উন্নত মেশিন লার্নিং মডেল",
    intelligentInsights: "বুদ্ধিমান অন্তর্দৃষ্টি",
    intelligentInsightsDesc: "ব্যক্তিগত সুপারিশ",
    voiceDocumentAI: "ভয়েস ও নথি AI",
    voiceDocumentDesc: "মাল্টি-মোডাল AI প্রক্রিয়াকরণ",
    uploading: "নথি আপলোড হচ্ছে...",
    extracting: "টেক্সট নিষ্কাশন করা হচ্ছে...",
    analyzing: "AI দিয়ে বিশ্লেষণ...",
    profileExtracted: "প্রোফাইল সফলভাবে নিষ্কাশিত!",
    complete: "সম্পূর্ণ!",
    processingFailed: "প্রক্রিয়াকরণ ব্যর্থ",
    tryAgain: "আবার চেষ্টা করুন",
    enterDetails: "আপনার বিবরণ প্রবেশ করুন",
    cancel: "বাতিল",
    analyzeText: "টেক্সট বিশ্লেষণ করুন",
    eligibilityResults: "যোগ্যতার ফলাফল",
    foundSchemes: "পাওয়া স্কিম",
    eligible: "যোগ্য",
    notEligible: "অযোগ্য",
    maybeEligible: "সম্ভাব্য যোগ্য",
    viewDetails: "বিবরণ দেখুন",
    applyNow: "এখনী আবেদন করুন",
    madeWithLove: "ভারতের জন্য সমর্পণ সহ তৈরি",
    privacyPolicy: "গোপনীয়তা নীতি",
    termsOfService: "সেবার শর্তাবলী",
    contactUs: "যোগাযোগ করুন"
  },
  
  TE: {
    searchPlaceholder: "పథకాలను వెతకండి...",
    login: "లాగిన్",
    logout: "లాగౌట్",
    settings: "సెట్టింగ్స్",
    heroTitle: "మీ AI-శక్తితో",
    heroSubtitle: "హక్కుల సహాయకుడు",
    heroDescription: "మీ పత్రాలను విశ్లేషించి, మీ అవసరాలను అర్థం చేసుకుని, దాచిన ప్రయోజనాలను కనుగొని వ్యక్తిగత సిఫార్సులను అందించే అధునాతన AI ప్లాట్‌ఫారమ్.",
    startAnalysis: "AI విశ్లేషణ ప్రారంభించండి",
    exploreTools: "AI టూల్స్ అన్వేషించండి",
    trustedUsers: "50,000+ వినియోగదారుల నమ్మకం",
    smartDocumentAI: "స్మార్ట్ డాక్యుమెంట్ AI",
    smartDocumentDesc: "99% ఖచ్చితత్వంతో ఎవరు డాక్యుమెంట్ రకాన్ని విశ్లేషించి విశ్లేషించుతుంది",
    personalizedInsights: "వ్యక్తిగత అంతర్దృష్టిలు",
    personalizedDesc: "మీ అనన్య ప్రొఫైల్కు అనుగుణంగా AI సిఫార్సులు",
    voiceTextAI: "వాయిస్ మరియు టెక్స్ట్ AI",
    voiceTextDesc: "12+ భాషలలో స్వాభావికంగా మాట్లాడండి లేదా వివరాలను టైప్ చేయండి",
    endToEndGuidance: "మొగించి కొనకు మార్గదర్శనం",
    endToEndDesc: "కనుగొనించి నుండి అర్జి పూర్తి వరకు",
    advancedAI: "అద్వితీయ AI బుద్ధిమత్త",
    intelligentAnalysis: "బుద్ధివంతమైన డాక్యుమెంట్ విశ్లేషణ",
    uploadDescription: "మా AI డాక్యుమెంట్లను అర్థం చేసుకుంటుంది, ప్రొఫైల్ విశ్లేషించుతుంది, అర్హతను విశ్లేషించుతుంది, దాచిన ప్రయోజనాలను కనుగొనుతుంది మరియు వ్యక్తిగత సిఫార్సులను అందిస్తుంది.",
    dragDrop: "డాక్యుమెంట్లను గెలి వేయండి",
    clickBrowse: "లేదా బ్రౌజ్ చేయడానికి క్లిక్ చేయండి • PDF, JPG, PNG సపోర్ట్ • గరిష్ఠం 10MB",
    takePhoto: "ఫోటో తీసుకోండి",
    takePhotoDesc: "మీ క్యామెరాతో డాక్యుమెంట్లను క్యాప్చర్ చేయండి",
    voiceInput: "వాయిస్ ఇన్పుట్",
    voiceInputDesc: "మీ వివరాలను చెప్పండి",
    typeDetails: "వివరాలను టైప్ చేయండి",
    typeDetailsDesc: "మీ సమాచారాన్ని మ్యానువల్గా ప్రవేశపెట్టండి",
    schemes: "పథకాలు",
    users: "వినియోగదారులు",
    languages: "భాషలు",
    successRate: "విజయ రేటు",
    aiModels: "AI మాడల్ల ఉపయోగం",
    aiAccuracy: "AI ఖచ్చితత్వం",
    aiAssistant: "AI సహాయకుడు",
    readyToStart: "ప్రారంభించడానికి తయారుగా?",
    experienceAI: "AI-శక్తి ప్రభుత్వ అనుభవించండి",
    ctaDescription: "అద్వితీయ AI 30 సెకన్ల కన్నా తక్కువ సమయంలో మీ ప్రొఫైల్ను విశ్లేషించి, దాచిన ప్రయోజనాలను కనుగొని వ్యక్తిగత మార్గదర్శనాన్ని అందిస్తుంది.",
    learnMore: "ఇంకా తెలుసుకోండి",
    aiPoweredAnalysis: "AI-శక్తి విశ్లేషణ",
    aiAnalysisDesc: "అద్వితీయ మెషిన్ లర్నింగ్ మాడల్లు",
    intelligentInsights: "బుద్ధివంతమైన అంతర్దృష్టిలు",
    intelligentInsightsDesc: "వ్యక్తిగత సిఫార్సులు",
    voiceDocumentAI: "వాయిస్ మరియు డాక్యుమెంట్ AI",
    voiceDocumentDesc: "మల్టి-మోడల్ AI ప్రోసెసింగ్",
    uploading: "డాక్యుమెంట్ అప్లోడ్ అవుతోంది...",
    extracting: "టెక్స్ట్ విశ్లేషించబడుతోంది...",
    analyzing: "AIతో విశ్లేషణ...",
    profileExtracted: "ప్రొఫైల్ విజయవంతంగా విశ్లేషించబడింది!",
    complete: "పూర్తి!",
    processingFailed: "ప్రోసెసింగ్ విఫలం",
    tryAgain: "మళ్లీ ప్రయత్నించండి",
    enterDetails: "మీ వివరాలను ప్రవేశపెట్టండి",
    cancel: "రద్దు చేయండి",
    analyzeText: "టెక్స్ట్ విశ్లేషించండి",
    eligibilityResults: "అర్హత ఫలితాలు",
    foundSchemes: "కనుగొన్న పథకాలు",
    eligible: "అర్హుడు",
    notEligible: "అర్హుడు కాదు",
    maybeEligible: "సాధారణంగా అర్హుడు",
    viewDetails: "వివరాలను చూడండి",
    applyNow: "ఇప్పుడే అర్జి చేయండి",
    madeWithLove: "భారతదేశానికి సమర్పణతో తయారు చేసినది",
    privacyPolicy: "గోప్యత నీతి",
    termsOfService: "సేవా నిబంధనలు",
    contactUs: "మాతో సంప్రదించండి"
  },
  
  MR: {
    searchPlaceholder: "योजना शोधा...",
    login: "लॉगिन",
    logout: "लॉगआउट",
    settings: "सेटिंग्ज",
    heroTitle: "तुमचा AI-चालित",
    heroSubtitle: "हक्क सहाय्यक",
    heroDescription: "तुमच्या कागदपत्रांचे विश्लेषण करणारे, तुमच्या गरजा समजून घेणारे, लपलेले फायदे शोधणारे आणि वैयक्तिक शिफारसी देणारे प्रगत AI प्लॅटफॉर्म.",
    startAnalysis: "AI विश्लेषण सुरू करा",
    exploreTools: "AI टूल्स एक्सप्लोर करा",
    trustedUsers: "50,000+ वापरकर्त्यांचा विश्वास",
    smartDocumentAI: "स्मार्ट दस्तऐवज AI",
    smartDocumentDesc: "99% अचूकतेसह कोणत्याही दस्तऐवज प्रकाराचे विश्लेषण आणि विश्लेषण",
    personalizedInsights: "वैयक्तिक अंतर्दृष्टी",
    personalizedDesc: "तुमच्या अनन्य प्रोफाइलसाठी AI शिफारसी",
    voiceTextAI: "आवाज आणि मजकूर AI",
    voiceTextDesc: "12+ भाषांमध्ये नैसर्गिकपणे बोला किंवा तपशील टाइप करा",
    endToEndGuidance: "संपूर्ण मार्गदर्शन",
    endToEndDesc: "शोधापासून अर्ज पूर्णतेपर्यंत",
    advancedAI: "प्रगत AI बुद्धिमत्ता",
    intelligentAnalysis: "बुद्धिमान दस्तऐवज विश्लेषण",
    uploadDescription: "आमचा AI दस्तऐवज समजतो, प्रोफाइल काढतो, पात्रतेचे विश्लेषण करतो, लपलेले फायदे शोधतो आणि वैयक्तिक शिफारसी देतो.",
    dragDrop: "दस्तऐवज ओढा आणि सोडा",
    clickBrowse: "किंवा ब्राउज करण्यासाठी क्लिक करा • PDF, JPG, PNG समर्थित • कमाल 10MB",
    takePhoto: "फोटो घ्या",
    takePhotoDesc: "तुमच्या कॅमेराने दस्तऐवज कॅप्चर करा",
    voiceInput: "आवाज इनपुट",
    voiceInputDesc: "तुमचे तपशील बोला",
    typeDetails: "तपशील टाइप करा",
    typeDetailsDesc: "तुमची माहिती मॅन्युअली एंटर करा",
    schemes: "योजना",
    users: "वापरकर्ते",
    languages: "भाषा",
    successRate: "यश दर",
    aiModels: "AI मॉडेल वापर",
    aiAccuracy: "AI अचूकता",
    aiAssistant: "AI सहाय्यक",
    readyToStart: "सुरू करण्यास तयार?",
    experienceAI: "AI-चालित शासनाचा अनुभव घ्या",
    ctaDescription: "प्रगत AI 30 सेकंदापेक्षा कमी वेळेत तुमच्या प्रोफाइलचे विश्लेषण करतो, लपलेले फायदे शोधतो आणि वैयक्तिक मार्गदर्शन देतो.",
    learnMore: "आणखी जाणून घ्या",
    aiPoweredAnalysis: "AI-चालित विश्लेषण",
    aiAnalysisDesc: "प्रगत मशीन लर्निंग मॉडेल",
    intelligentInsights: "बुद्धिमान अंतर्दृष्टी",
    intelligentInsightsDesc: "वैयक्तिक शिफारसी",
    voiceDocumentAI: "आवाज आणि दस्तऐवज AI",
    voiceDocumentDesc: "मल्टी-मोडल AI प्रोसेसिंग",
    uploading: "दस्तऐवज अपलोड होत आहे...",
    extracting: "मजकूर काढला जात आहे...",
    analyzing: "AI सह विश्लेषण...",
    profileExtracted: "प्रोफाइल यशस्वीपणे काढले!",
    complete: "पूर्ण!",
    processingFailed: "प्रोसेसिंग अयशस्वी",
    tryAgain: "पुन्हा प्रयत्न करा",
    enterDetails: "तुमचे तपशील एंटर करा",
    cancel: "रद्द करा",
    analyzeText: "मजकूर विश्लेषण करा",
    eligibilityResults: "पात्रता परिणाम",
    foundSchemes: "मिळालेल्या योजना",
    eligible: "पात्र",
    notEligible: "अपात्र",
    maybeEligible: "कदाचित पात्र",
    viewDetails: "तपशील पहा",
    applyNow: "आताच अर्ज करा",
    madeWithLove: "भारतासाठी समर्पणाने बनवले",
    privacyPolicy: "गोपनीयता धोरण",
    termsOfService: "सेवा अटी",
    contactUs: "आमच्याशी संपर्क करा"
  },
  
  TA: {
    searchPlaceholder: "திட்டங்களைத் தேடுங்கள்...",
    login: "உள்நுழைவு",
    logout: "வெளியேறு",
    settings: "அமைப்புகள்",
    heroTitle: "உங்கள் AI-இயங்கும்",
    heroSubtitle: "உரிமைகள் உதவியாளர்",
    heroDescription: "உங்கள் ஆவணங்களை பகுப்பாய்வு செய்து, உங்கள் தேவைகளை புரிந்துகொண்டு, மறைக்கப்பட்ட நன்மைகளை கண்டறிந்து தனிப்பட்ட பரிந்துரைகளை வழங்கும் மேம்பட்ட AI தளம்.",
    startAnalysis: "AI பகுப்பாய்வு தொடங்கு",
    exploreTools: "AI கருவிகளை ஆராயுங்கள்",
    trustedUsers: "50,000+ பயனர்களின் நம்பிக்கை",
    smartDocumentAI: "ஸ்மார்ட் ஆவணம் AI",
    smartDocumentDesc: "99% தெளிவுடன் எந்த ஆவண வகையையும் விளக்கி பகுப்பாய்வு செய்கிறது",
    personalizedInsights: "தனிப்பட்ட அறிவுகள்",
    personalizedDesc: "உங்கள் தனித்துவமான சுவடுக்கு ஏற்ற AI பரிந்துரைகள்",
    voiceTextAI: "குரல் மற்றும் உரை AI",
    voiceTextDesc: "12+ மொழிகளில் இயல்பாக பேசுங்கள் அல்லது விவரங்களை டைப் செய்யுங்கள்",
    endToEndGuidance: "முடிவிலிருந்து முடிவரை வழிகாட்டல்",
    endToEndDesc: "கண்டுபிடிப்பதிலிருந்து விண்ணப்ப முடிவவரை",
    advancedAI: "மேம்பட்ட AI அறிவு",
    intelligentAnalysis: "அறிவுமிக்க ஆவண பகுப்பாய்வு",
    uploadDescription: "எங்கள் AI ஆவணங்களை புரிந்துகொள்கிறது, சுவடுக்கை விளக்குகிறது, தகுதியை பகுப்பாய்வு செய்கிறது, மறைக்கப்பட்ட நன்மைகளை கண்டுபிடிக்கிறது மற்றும் தனிப்பட்ட பரிந்துரைகளை வழங்குகிறது.",
    dragDrop: "ஆவணங்களை இழுத்து விடுங்கள்",
    clickBrowse: "அல்லது பிரவுச க்லிக் செய்யுங்கள் • PDF, JPG, PNG ஆதரவு • அதிகபட்சம் 10MB",
    takePhoto: "படம் எடுங்கள்",
    takePhotoDesc: "உங்கள் கேமராவில் ஆவணங்களை கைப்பிடுங்கள்",
    voiceInput: "குரல் உள்ளீடு",
    voiceInputDesc: "உங்கள் விவரங்களை சொல்லுங்கள்",
    typeDetails: "விவரங்களை டைப் செய்யுங்கள்",
    typeDetailsDesc: "உங்கள் தகவலை கையால் உள்ளீடுங்கள்",
    schemes: "திட்டங்கள்",
    users: "பயனர்கள்",
    languages: "மொழிகள்",
    successRate: "வெற்றி வீதம்",
    aiModels: "AI மாடல்கள் பயன்பாடு",
    aiAccuracy: "AI தெளிவு",
    aiAssistant: "AI உதவியாளர்",
    readyToStart: "தொடங்க தயாரா?",
    experienceAI: "AI-இயங்கும் ஆட்சியை அனுபவிக்குங்கள்",
    ctaDescription: "மேம்பட்ட AI 30 விநாடிகளில் உங்கள் சுவடுக்கை பகுப்பாய்வு செய்து, மறைக்கப்பட்ட நன்மைகளை கண்டுபிடித்து தனிப்பட்ட வழிகாட்டலை வழங்குகிறது.",
    learnMore: "மேலும் அறியுங்கள்",
    aiPoweredAnalysis: "AI-இயங்கும் பகுப்பாய்வு",
    aiAnalysisDesc: "மேம்பட்ட இயந்திர கற்றல் மாடல்கள்",
    intelligentInsights: "அறிவுமிக்க அறிவுகள்",
    intelligentInsightsDesc: "தனிப்பட்ட பரிந்துரைகள்",
    voiceDocumentAI: "குரல் மற்றும் ஆவணம் AI",
    voiceDocumentDesc: "பல-மாடல் AI செயலாக்கம்",
    uploading: "ஆவணம் பதிவேற்றப்படுகிறது...",
    extracting: "உரை விளக்கப்படுகிறது...",
    analyzing: "AI மூலம் பகுப்பாய்வு...",
    profileExtracted: "சுவடு வெற்றிகரமாக விளக்கப்பட்டது!",
    complete: "முடிவு!",
    processingFailed: "செயலாக்கம் தோல்வி",
    tryAgain: "மீண்டும் முயற்சி செய்யுங்கள்",
    enterDetails: "உங்கள் விவரங்களை உள்ளீடுங்கள்",
    cancel: "ரத்து செய்யுங்கள்",
    analyzeText: "உரை பகுப்பாய்வு செய்யுங்கள்",
    eligibilityResults: "தகுதி முடிவுகள்",
    foundSchemes: "கண்டுபிடிக்கப்பட்ட திட்டங்கள்",
    eligible: "தகுதியுள்ளவர்",
    notEligible: "தகுதியற்றவர்",
    maybeEligible: "எதிர்பார்க்கலாம் தகுதியுள்ளவர்",
    viewDetails: "விவரங்களை பார்க்குங்கள்",
    applyNow: "இப்போதே விண்ணப்பிக்குங்கள்",
    madeWithLove: "இந்தியாவிற்காக அர்ப்பணிப்புடன் செய்யப்பட்டது",
    privacyPolicy: "தனியுரிமை கொள்கை",
    termsOfService: "சேவை நிபந்தனைகள்",
    contactUs: "எங்களை தொடர்பு கொள்ளுங்கள்"
  },
  
  GU: {
    searchPlaceholder: "યોજનાઓ શોધો...",
    login: "લોગિન",
    logout: "લોગઆઉટ",
    settings: "સેટિંગ્સ",
    heroTitle: "તમારું AI-સંચાલિત",
    heroSubtitle: "અધિકાર સહાયક",
    heroDescription: "તમારા દસ્તાવેજોનું વિશ્લેષણ કરતું, તમારી જરૂરિયાતો સમજતું, છુપાયેલા ફાયદા શોધતું અને વ્યક્તિગત ભલામણો આપતું અદ્યતન AI પ્લેટફોર્મ.",
    startAnalysis: "AI વિશ્લેષણ શરૂ કરો",
    exploreTools: "AI ટૂલ્સ અન્વેષણ કરો",
    trustedUsers: "50,000+ વપરાશકર્તાઓનો વિશ્વાસ"
  },
  
  KN: {
    searchPlaceholder: "ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ...",
    login: "ಲಾಗಿನ್",
    logout: "ಲಾಗೌಟ್",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    heroTitle: "ನಿಮ್ಮ AI-ಚಾಲಿತ",
    heroSubtitle: "ಹಕ್ಕುಗಳ ಸಹಾಯಕ",
    heroDescription: "ನಿಮ್ಮ ದಾಖಲೆಗಳನ್ನು ವಿಶ್ಲೇಷಿಸುವ, ನಿಮ್ಮ ಅಗತ್ಯಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವ, ಗುಪ್ತ ಪ್ರಯೋಜನಗಳನ್ನು ಕಂಡುಹಿಡಿಯುವ ಮತ್ತು ವೈಯಕ್ತಿಕ ಶಿಫಾರಸುಗಳನ್ನು ನೀಡುವ ಸುಧಾರಿತ AI ವೇದಿಕೆ.",
    startAnalysis: "AI ವಿಶ್ಲೇಷಣೆ ಪ್ರಾರಂಭಿಸಿ",
    exploreTools: "AI ಉಪಕರಣಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
    trustedUsers: "50,000+ ಬಳಕೆದಾರರ ನಂಬಿಕೆ"
  },
  
  ML: {
    searchPlaceholder: "പദ്ധതികൾ തിരയുക...",
    login: "ലോഗിൻ",
    logout: "ലോഗൗട്ട്",
    settings: "ക്രമീകരണങ്ങൾ",
    heroTitle: "നിങ്ങളുടെ AI-പവർഡ്",
    heroSubtitle: "അവകാശ സഹായി",
    heroDescription: "നിങ്ങളുടെ രേഖകൾ വിശകലനം ചെയ്യുന്ന, നിങ്ങളുടെ ആവശ്യങ്ങൾ മനസ്സിലാക്കുന്ന, മറഞ്ഞിരിക്കുന്ന ആനുകൂല്യങ്ങൾ കണ്ടെത്തുന്ന, വ്യക്തിഗത ശുപാർശകൾ നൽകുന്ന വിപുലമായ AI പ്ലാറ്റ്ഫോം.",
    startAnalysis: "AI വിശകലനം ആരംഭിക്കുക",
    exploreTools: "AI ടൂളുകൾ പര്യവേക്ഷണം ചെയ്യുക",
    trustedUsers: "50,000+ ഉപയോക്താക്കളുടെ വിശ്വാസം"
  },
  
  PA: {
    searchPlaceholder: "ਸਕੀਮਾਂ ਖੋਜੋ...",
    login: "ਲਾਗਇਨ",
    logout: "ਲਾਗਆਉਟ",
    settings: "ਸੈਟਿੰਗਾਂ",
    heroTitle: "ਤੁਹਾਡਾ AI-ਸੰਚਾਲਿਤ",
    heroSubtitle: "ਅਧਿਕਾਰ ਸਹਾਇਕ",
    heroDescription: "ਤੁਹਾਡੇ ਦਸਤਾਵੇਜ਼ਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰਨ ਵਾਲਾ, ਤੁਹਾਡੀਆਂ ਲੋੜਾਂ ਨੂੰ ਸਮਝਣ ਵਾਲਾ, ਛੁਪੇ ਹੋਏ ਫਾਇਦੇ ਲੱਭਣ ਵਾਲਾ ਅਤੇ ਨਿੱਜੀ ਸਿਫਾਰਸ਼ਾਂ ਦੇਣ ਵਾਲਾ ਉੱਨਤ AI ਪਲੇਟਫਾਰਮ।",
    startAnalysis: "AI ਵਿਸ਼ਲੇਸ਼ਣ ਸ਼ੁਰੂ ਕਰੋ",
    exploreTools: "AI ਟੂਲਸ ਦੀ ਖੋਜ ਕਰੋ",
    trustedUsers: "50,000+ ਉਪਭੋਗਤਾਵਾਂ ਦਾ ਭਰੋਸਾ"
  },
  
  OR: {
    searchPlaceholder: "ଯୋଜନା ଖୋଜନ୍ତୁ...",
    login: "ଲଗଇନ୍",
    logout: "ଲଗଆଉଟ୍",
    settings: "ସେଟିଂସ୍",
    heroTitle: "ଆପଣଙ୍କର AI-ଚାଳିତ",
    heroSubtitle: "ଅଧିକାର ସହାୟକ",
    heroDescription: "ଆପଣଙ୍କ ଦଲିଲଗୁଡ଼ିକର ବିଶ୍ଳେଷଣ କରୁଥିବା, ଆପଣଙ୍କ ଆବଶ୍ୟକତା ବୁଝୁଥିବା, ଲୁଚି ରହିଥିବା ସୁବିଧା ଖୋଜୁଥିବା ଏବଂ ବ୍ୟକ୍ତିଗତ ସୁପାରିଶ ପ୍ରଦାନ କରୁଥିବା ଉନ୍ନତ AI ପ୍ଲାଟଫର୍ମ।",
    startAnalysis: "AI ବିଶ୍ଳେଷଣ ଆରମ୍ଭ କରନ୍ତୁ",
    exploreTools: "AI ଉପକରଣଗୁଡ଼ିକ ଅନ୍ବେଷଣ କରନ୍ତୁ",
    trustedUsers: "50,000+ ଉପଭୋକ୍ତାଙ୍କ ବିଶ୍ୱାସ"
  },
  
  AS: {
    searchPlaceholder: "আঁচনি বিচাৰক...",
    login: "লগইন",
    logout: "লগআউট",
    settings: "ছেটিংছ",
    heroTitle: "আপোনাৰ AI-চালিত",
    heroSubtitle: "অধিকাৰ সহায়ক",
    heroDescription: "আপোনাৰ নথি-পত্ৰ বিশ্লেষণ কৰা, আপোনাৰ প্ৰয়োজনীয়তা বুজা, লুকাই থকা সুবিধা আৱিষ্কাৰ কৰা আৰু ব্যক্তিগত পৰামৰ্শ প্ৰদান কৰা উন্নত AI প্লেটফৰ্ম।",
    startAnalysis: "AI বিশ্লেষণ আৰম্ভ কৰক",
    exploreTools: "AI সঁজুলি অন্বেষণ কৰক",
    trustedUsers: "50,000+ ব্যৱহাৰকাৰীৰ বিশ্বাস"
  },
  
  UR: {
    searchPlaceholder: "اسکیمز تلاش کریں...",
    login: "لاگ ان",
    logout: "لاگ آؤٹ",
    settings: "سیٹنگز",
    heroTitle: "آپ کا AI-طاقتور",
    heroSubtitle: "حقوق کا معاون",
    heroDescription: "آپ کے دستاویزات کا تجزیہ کرنے والا، آپ کی ضروریات کو سمجھنے والا، چھپے ہوئے فوائد تلاش کرنے والا اور ذاتی تجاویز فراہم کرنے والا جدید AI پلیٹ فارم۔",
    startAnalysis: "AI تجزیہ شروع کریں",
    exploreTools: "AI ٹولز کی تلاش کریں",
    trustedUsers: "50,000+ صارفین کا اعتماد"
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('EN');
  
  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations.EN[key] || key;
  };
  
  const changeLanguage = (lang) => {
    setCurrentLanguage(lang);
  };
  
  return (
    <LanguageContext.Provider value={{ 
      currentLanguage, 
      changeLanguage, 
      t 
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};